require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
 

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7.4

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Max: 50

Metrics/AbcSize:
  Max: 50

RSpec/MultipleExpectations:
  Max: 10

RSpec/ExampleLength:
  Max: 20
