name: RSpec
on: [pull_request]
jobs:
  test:
    services:
      db:
        image: postgres:latest
        ports: ['5432:5432']
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: actions/setup-ruby@v1.1.3
        with:
          ruby-version: 2.7.4


      - uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Build and run tests
        env:
          DATABASE_URL: postgres://postgres:@localhost:5432/roots_test
          POSTGRES_PASSWORD: postgres
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bundle install
          bundle exec rails db:prepare
          bundle exec rspec
