name: RSpec
on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
jobs:
  test:
    services:
      db:
        image: postgres:latest
        ports: ['5432:5432']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: actions/setup-ruby@v1.1.3
        with:
          ruby-version: 2.7.4
      - name: Build and run tests
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bundle install
          bundler exec rails db:create
          bundler exec rails db:migrate
          bundle exec rspec
